### ISSUE TITLE
Having a "/" before directory search pattern breaks picker

### ISSUE THREAD

**Issue by ziontee113** [nvim-telescope/telescope-live-grep-args.nvim#31]
Thank you for the amazing plugin. I finally learned how to use it and it's awesome!

One problem that I ran into is in this scenario: type in the prompt `"your search term" /`
What I meant to do was `"your search term" /tests`, which the correct syntax is `"your search term" tests`

But instead of returning no results and the picker works just fine, the picker is now not responding to user input (prompt change), which renders it useless. The user would have to close the picker and start again.

This seems to be ripgrep's problem. But since I'm new to ripgrep, I don't know if this my fault or something else.

**Comment by weeman1337** [comment]
Hi @ziontee113 . `"your search term" /` will grep your entire system from root.
`"your search term" /tests` then will grep in your root `test` directory. I assume this is empty so you won't get any results.

Since I cannot see anything that I can do here I will close the issue. If you have further questions you can post them here.
